"""add timedelta column to the charity_project table

Revision ID: b4a3855962ad
Revises: 5675ad85645b
Create Date: 2025-01-23 18:09:38.505787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a3855962ad'
down_revision = '5675ad85645b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('timedelta', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'timedelta')
    # ### end Alembic commands ###
